### PR TITLE
[BugFix] Solve issues-3470: Yarn webui fails to obtain task status when submitting a Flink task after turning on Kerberos authentication.

### LINKED ISSUE #3470: [Bug] [Flink] In version 1.0.2 of the YARN service, the Flink task cannot obtain the status after enabling the Kerberos authentication of the HTTP Web console.
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

验证环境：
dinky 1.0.2
flink 1.17.0
CDH6.3.2 

问题:
YARN服务 启用 HTTP Web 控制台的 Kerberos 身份验证后  application模式或者 perjob模式无法获取到任务状态
递交时候获取状态报错
2024-05-10 16:26:37.939 ERROR org.dinky.gateway.AbstractGateway(402): Yarn application state is not running, please check yarn cluster status. Log content:     Authentication required
image

虽然最后递交成功时候拿到返回状态，但是在运维中心查看不到任务
image
返回数据开发页面   重新点击打开任务页面也找不到状态了  
image

### What you expected to happen

YARN服务启用 HTTP Web 控制台的 Kerberos 身份验证后 也能正常拿到状态

### How to reproduce

创建flink sql任务 使用官网demo代码
https://www.dinky.org.cn/docs/next/practical_guide/Integration_practice/dinky_integration_flink#%E5%88%9B%E5%BB%BA-datagen-%E4%BB%BB%E5%8A%A1

使用application或者perjob模式时虽然最后递交成功  但中间有报错   后续也拿不到状态
2024-05-10 16:23:46.438 ERROR org.dinky.gateway.AbstractGateway(402): Yarn application state is not running, please check yarn cluster status. Log content:     Authentication required
2024-05-10 16:23:48.447 ERROR org.dinky.gateway.AbstractGateway(402): Yarn application state is not running, please check yarn cluster status. Log content:     Authentication required
2024-05-10 16:23:50.457 ERROR org.dinky.gateway.AbstractGateway(402): Yarn application state is not running, please check yarn cluster status. Log content:     Authentication required
2024-05-10 16:23:52.466 ERROR org.dinky.gateway.AbstractGateway(402): Yarn application state is not running, please check yarn cluster status. Log content:     Authentication required
2024-05-10 16:23:52.666 INFO  org.dinky.service.impl.TaskServiceImpl(192): execute job finished,status is SUCCESS
Process Step SUBMIT_EXECUTE exit with status:FINISHED
2024-05-10 16:23:52.666 INFO  org.dinky.service.impl.TaskServiceImpl(323): Job Submit success

### Anything else

_No response_

### Version

1.0.2

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by miaoze8**
解决yarn webui开启Kerberos认证后递交Flink任务无法获取任务状态的问题，增加调用Flink HTTP API时候进行Kerberos认证，
相关issues: https://github.com/DataLinkDC/dinky/issues/3470

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

### CODE REVIEW

**Comment by zackyoungh** [comment]
请使用spotless 格式化代码,详细查看此文：https://www.dinky.org.cn/docs/next/developer_guide/contribution/pull_request#pull-request-code-style

**Review by miaoze8 — COMMENTED** [review]
已用spotless 格式化代码

**Review by miaoze8 — COMMENTED** [review]
已调整

**Review by miaoze8 — COMMENTED** [review]
调整 import x.*

File: dinky-gateway/src/main/java/org/dinky/gateway/yarn/YarnGateway.java [hunk 1]
```diff
@@ -106,6 +111,8 @@ public abstract class YarnGateway extends AbstractGateway {
 
     protected YarnClient yarnClient;
 
+    private static boolean ENABLE_KERBEROS_AUTH = false;
+
```
Comment (aiwenmo) [inline dinky-gateway/src/main/java/org/dinky/gateway/yarn/YarnGateway.java]: Some clusters require Kerberos authentication, while others do not. It should be determined based on the cluster configuration instead of being uniformly set.

**Review by aiwenmo — COMMENTED** [review]
Hi. Thank you for your contribution. I have a question.

**Review by miaoze8 — COMMENTED** [review]
更改判断方式，仅在获取flink任务状态时候HTTP如果返回401状态时，额外采用Kerberos方式认证HTTP获取flink任务状态

File: dinky-gateway/src/main/java/org/dinky/gateway/utils/RequestKerberosUrlUtils.java [hunk 2]
```diff
@@ -0,0 +1,158 @@
...
+    }
+
+    public RequestKerberosUrlUtils(String principal, String keyTabLocation, boolean isDebug) {
+        this(principal, keyTabLocation);
+        if (isDebug) {
+            System.setProperty("sun.security.spnego.debug", "true");
+            System.setProperty("sun.security.krb5.debug", "true");
+        }
+    }
+
```
Comment (aiwenmo) [inline dinky-gateway/src/main/java/org/dinky/gateway/utils/RequestKerberosUrlUtils.java:71]: Under what circumstances will the isDebug parameter be true? Currently, only the use of false is in the code.

Comment (miaoze8) [reply dinky-gateway/src/main/java/org/dinky/gateway/utils/RequestKerberosUrlUtils.java:71]: 这个一般用不到，例如开发时候Kerberos认证失败普通报错找不到原因时候，才用这个参数开启kerberos debug日志进一步找问题，目前只用false，不需要开启true。

**Comment by aiwenmo** [comment]
Hi. Run 'mvn spotless:apply' to fix these violations.

**Review by miaoze8 — COMMENTED** [review]
spotless:apply done

**Review by aiwenmo — APPROVED** [review]
LGTM
