### PR TITLE
[Optimization-2284][web] Optimize dinky web and fix some bugs

### LINKED ISSUE #2284: [Optimization][web] Optimize dinky web and fix some bugs
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar optimization requirement.

### Description

_No response_

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by aiwenmo**
## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

### CODE REVIEW

File: dinky-web/src/pages/Home/DevOverView/index.tsx [hunk 1]
```diff
@@ -48,9 +53,10 @@ const DevOverView: React.FC = () => {
         bordered
         size='small'
         split={split}
+        bodyStyle={noPadding}
       >
-        <ProCard split='vertical'>
-          <ProCard split='horizontal' colSpan={'40%'}>
+        <ProCard split='vertical' bodyStyle={noPadding}>
```
Comment (Zzm0809) [inline dinky-web/src/pages/Home/DevOverView/index.tsx:58]: use ghost

**Review by Zzm0809 — APPROVED** [review]
LGTM
