### PR TITLE
[Fix-4191][Fix-4288] fix jar sqlstatement split

### LINKED ISSUE #4191: [Bug] [Admin][Jar Task]When the jar task statement contains "--" comments, the response from the `flinkJarSqlConvertForm` interface is abnormal.
### Search before asking

- [x] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

When I add a comment statement starting with "--" to the statement in the JAR task and save it, the comment statement, and even the entire page, cannot be displayed correctly when I reopen the task page. 
(However, the statement in the JSON response from the interface is complete and correct.) 

For detailed information, please refer to the "How to reproduce" section below.

### What you expected to happen

The editing page of the JAR task should display and handle comment statements starting with "--" correctly.

### How to reproduce

Create a JAR task and fill in the execute JAR information normally.
Case 1:
1.1 Add a single comment line in the task statement and save it.
1.2 Close the task tab and reopen it.
1.3 The interface returns the complete statement, but the comment in the editing window disappears.

Image

Case 2:
2.1 Add multiple comment lines at the end of the task statement and save it.
2.2 Close the task tab and reopen it.
2.3 The interface returns the complete statement, but the editing window is cleared.

Image

Case 3:
3.1 Add multiple comment lines and add a normal SET statement at the end of the task statement, then save it.
3.2 Close the task tab and reopen it.
3.3 The interface returns the complete statement, but the first line of the comment in the editing window disappears.

Image

### Anything else

_No response_

### Version

1.2.1

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by jiangwwwei**
## Purpose of the pull request
This PR resolves #4191  
and #4288

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

### CODE REVIEW

File: dinky-admin/src/main/java/org/dinky/controller/TaskController.java [hunk 1]
```diff
@@ -315,21 +315,47 @@ public Result<FlinkJarSqlConvertVO> flinkJarSqlConvertForm(@RequestBody TaskDTO
...
+          If the statement before "EXECUTE JAR WITH" is not correctly terminated with a semicolon (";"),
+        it will not be properly matched by ExecuteJarParseStrategyUtil.match().
+        However, this splitting method might treat multiple "EXECUTE JAR WITH" statements as a single statement for
+        processing. Therefore, it is preferable to use the preceding splitting method.
+
+        中文:
+          如果EXECUTE JAR WITH前的语句没有正确的使用";"来结束，将无法匹配ExecuteJarParseStrategyUtil.match()，只能手动切分;
+          但是这个切分方法可能会把多个EXECUTE JAR WITH语句当作一个进行处理，因此优先使用前面的切分方法
+        */
+        String regex = "(?is)(\\n *|^ *)EXECUTE\\s+JAR\\s+WITH\\s*\\(.+\\)\\s*;?\\s*";
```
Comment (aiwenmo) [inline dinky-admin/src/main/java/org/dinky/controller/TaskController.java]: Execute Jar is an extended implementation syntax. We shouldn't perform special handling here. Instead, it should be transformed into a common problem for fixing. For example, test whether other syntaxes encounter this problem in such a situation. If so, handle it uniformly here.
Execute Jar 是一个扩展实现语法，我们不应该在此处进行特殊处理，应该转化为共同问题修复。比如测试其他语法在遇到这个情况时是否会出现该问题，如果出现，则在此处统一处理。

**Review by aiwenmo — CHANGES_REQUESTED** [review]

File: dinky-admin/src/main/java/org/dinky/controller/TaskController.java (hunk 1 above)
Comment (jiangwwwei) [reply dinky-admin/src/main/java/org/dinky/controller/TaskController.java]: The 'EXECUTE JAR' statement is stored together with other statements, which may be affected by abnormal statements and thus fail to match correctly and completely. This is different from other extended syntaxes, where abnormalities only lead to execution failure. However, an incorrect 'EXECUTE JAR' directly causes the loss of task information returned by the interface.

Although we have implemented a logic to return all original data to initSqlStatement when 'EXECUTE JAR' is not matched, the original args of 'EXECUTE JAR' have already been converted into base64-encoded characters, which are difficult for users to handle. Therefore, it is still necessary to try to match and parse 'EXECUTE JAR' as much as possible. That's why I modified the matching rules of ExecuteJarParseStrategy this time.

If possible, storing 'EXECUTE JAR' separately in the future would likely be a better approach to handle these issues.

----
'EXECUTE JAR'与其他statement存储在一起，可能被异常的statement影响，从而无法正常完整匹配。
这与其他拓展语法是不同的，其他语法的异常只会导致执行失败，而不正确'EXECUTE JAR'会直接导致接口返回的任务信息丢失。

虽然已经增加了未匹配到'EXECUTE JAR'时返回所有原始数据到initSqlStatement的逻辑，
但是原始'EXECUTE JAR'的args已经变成了base64编码的字符，用户难以处理，
因此还是需要尽量匹配上'EXECUTE JAR'并解析，所以我这次修改了ExecuteJarParseStrategy的匹配规则

如果可以的话，将来单独存储EXECUTE JAR应该会更好处理这些问题

File: dinky-common/src/main/java/org/dinky/utils/SqlUtil.java [hunk 2]
```diff
@@ -40,19 +41,42 @@ public static String[] getStatements(String sql) {
...
+    /**
+     * This method only splits valid statements.
+     * First, remove all comments.
+     * Then, use semicolons (;) not enclosed in single quotes as the splitting delimiter and trim the results.
+     * @param sql
+     * @param sqlSeparator
+     * @return statement string array
+     */
     public static String[] getStatements(String sql, String sqlSeparator) {
         if (Asserts.isNullString(sql)) {
```
Comment (aiwenmo) [inline dinky-common/src/main/java/org/dinky/utils/SqlUtil.java:53]: Since the changes to this method have a significant impact, please add necessary unit tests.
由于这个方法改动影响较大，请补充必要的单元测试。

Comment (jiangwwwei) [reply dinky-common/src/main/java/org/dinky/utils/SqlUtil.java:53]: 好的，我添加了复杂注释的sql和e2e_test中的sql测试用例，

原来的旧方法在应对互相嵌套的注释、分号、单引号时会出现问题
这个方法现在的逻辑是
1.先把注释清除，防止注释内容影响后续的切分。
2.把不被''包裹的;作为切分符进行切分
3.清除前后的空字符。

Sure, I have added the SQL test cases with complex comments and in the e2e_test.
The old method had issues when dealing with nested comments, semicolons, and single quotes.
The logic of this new method is as follows:
1.First, remove the comments to prevent their content from affecting the subsequent splitting.
2.Use the semicolon (;) that is not enclosed in single quotes ('') as the delimiter for splitting.
3,Trim the leading and trailing whitespace characters.

**Review by aiwenmo — APPROVED** [review]
LGTM

**Comment by aiwenmo** [comment]
Hi. thx your fix. This pull request will be merged into Dinky v1.2.4.
