### PR TITLE
[BugFix][FlinkSQL] V1.1.0 version Keberos bug related repair, SQL SET value does not take effect, etc

### LINKED ISSUE #3874: [Bug] [HIVE] Did not correctly interpret the Hive table creation statement, but the older version 0.7.1 works.
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

env info:
dinky: v1.10
jdk: jdk8
flink: flink1.14.6

sql  is show as flow
```sql
SET execution.checkpointing.interval = 12h;
SET execution.checkpointing.tolerable-failed-checkpoints = 3;
SET execution.checkpointing.timeout = 300s;
SET execution.checkpointing.externalized-checkpoint-retention = RETAIN_ON_CANCELLATION;
SET execution.checkpointing.mode = EXACTLY_ONCE;
SET execution.checkpointing.unaligned = true;
SET pipeline.operator-chaining = false;
SET yarn.application.queue=queue_3001_02;
set table.exec.state.ttl=60000;

SET table.sql-dialect=hive;
CREATE CATALOG myhive WITH (
    'type' = 'hive',
    'default-database' = '${imeg_hive_db_name}',
    'hive-conf-dir' = '/appcom/config/hive-config',
    'hadoop-conf-dir'='/appcom/config/hadoop-config'
);

USE CATALOG myhive;
use ${imeg_hive_db_name};
CREATE TABLE IF NOT EXISTS `ilh_turingshield_txn_detl` (
    bizSeqNo string,
    channel string,
    mpcUid string,
    deviceId string,
    riskDeviceId string,
    riskLevel string,
    riskType string,
    extraInfo string,
    requestId string,
    tokenTime string,
    userAction string
) PARTITIONED BY (ds string) STORED AS orc TBLPROPERTIES (
  'partition.time-extractor.timestamp-pattern'='$ds 00:00:00',
  'sink.partition-commit.trigger'='partition-time',
  'sink.partition-commit.delay'='0 s',
  'sink.partition-commit.policy.kind'='metastore',
  'orc.compress' = 'SNAPPY',
  'auto-compaction' = 'true',
  'sink.rolling-policy.rollover-interval' = '12 h',
  'sink.shuffle-by-partition.enable' = 'true',
  'sink.parallelism' = '1'
);

SET table.sql-dialect=default;

drop table if exists ilh_turingshield_txn_kfk;
create table if not exists ilh_turingshield_txn_kfk(
  `event_time` TIMESTAMP(3) METADATA FROM 'timestamp',
   `partition_id` BIGINT METADATA FROM 'partition' VIRTUAL,  -- from Kafka connector
    `offset` BIGINT METADATA VIRTUAL,  -- from Kafka connector
    bizSeqNo string,
    channel string,
    mpcUid string,
    deviceId string,
    riskDeviceId string,
    riskLevel string,
    riskType string,
    extraInfo string,
    requestId string,
    tokenTime string,
    userAction string,
    proctime as PROCTIME(),
    WATERMARK FOR event_time as event_time - INTERVAL '10' SECOND
) WITH (
  'connector' = 'kafka',
  'topic' = 'tcbtrd_ilh_turingshield_txn',
  'properties.bootstrap.servers' = '${kafka_bootstrap_servers}',
  'properties.group.id' = 'turingshield_01',
  'scan.startup.mode' = 'group-offsets',
  'value.format' = 'json',
  'value.json.fail-on-missing-field' = 'false',
  'value.json.ignore-parse-errors' = 'true',
  'properties.security.protocol' = 'SASL_PLAINTEXT',
  'properties.sasl.mechanism' = 'GSSAPI',
  'properties.sasl.kerberos.service.name' = 'hadoop',
  'properties.sasl.jaas.config' = 'com.sun.security.auth.module.Krb5LoginModule required useKeyTab=true keyTab="/appcom/keytab/hduser3001.keytab" storeKey=true useTicketCache=false principal="hduser3001@WEBANK.COM";'
);

INSERT INTO ilh_turingshield_txn_detl 
SELECT 
bizSeqNo,
channel,
mpcUid,
deviceId,
riskDeviceId,
riskLevel,
riskType,
extraInfo,
requestId,
tokenTime,
userAction,
DATE_FORMAT(event_time, 'yyyy-MM-dd')
FROM ilh_turingshield_txn_kfk;
```
But the prompt is：
image
but is normal in version v0.7.1
image

### What you expected to happen

i debug step by step :
in version v1.1.0 ，the currentDialect is DEFATLT
image

but in version v0.7.1,the currentDialect is HIVE
image

### How to reproduce

Hive SQL described above

### Anything else

_No response_

### Version

1.1.0

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by chenhaipeng**
Fix the following issues:

Feature:

1. Added getJobInstanceListapi in APIController.
2. table.topic.map, using topic:tableName,eg: topic1:tableA;topic2:tableB,tableC, can reduce the creation of topics.

Fix:
1. FlinkAPI Kerberos might start with http or https.
2. In ExecutorConfig, if the address starts with http://xx, the splitting is incorrect.
3. Fixed value passing issue in KafkaSinkBuilder, where DeliveryGuarantee was always set to EXACTLY_ONCE because the default submission is in Dinky.
4. Fixed the issue where the environment variable set 'xxxx' in MysqlCDCBuilder SQL did not take effect.
5. Fixed the redirection issue in JobOperator.tsx.

Pending:

https://github.com/DataLinkDC/dinky/issues/3874#issuecomment-2419108471
PS: Thanks to the community for contributing such a useful tool!

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

### CODE REVIEW

File: dinky-cdc/dinky-cdc-core/src/main/java/org/dinky/cdc/AbstractSinkBuilder.java [hunk 1]
```diff
@@ -587,4 +590,26 @@ protected List<String> getPKList(Table table) {
     protected ZoneId getSinkTimeZone() {
         return this.sinkTimeZone;
     }
+
+    protected Map<String, String> getTableTopicMap() {
```
Comment (Zzm0809) [inline dinky-cdc/dinky-cdc-core/src/main/java/org/dinky/cdc/AbstractSinkBuilder.java:594]: 不应该在 `dinky-cdc/dinky-cdc-core/src/main/java/org/dinky/cdc/AbstractSinkBuilder.java` 中写此方法 因为不属于公共抽象方法 建议下沉到 kafkasinkbuilder

File: dinky-cdc/dinky-cdc-core/src/main/java/org/dinky/cdc/AbstractSinkBuilder.java [hunk 2]
```diff
@@ -131,7 +131,10 @@ protected Properties getProperties() {
                     && entry.getKey().startsWith("properties")
                     && Asserts.isNotNullString(entry.getValue())) {
                 properties.setProperty(entry.getKey().replace("properties.", ""), entry.getValue());
+            } else {
+                properties.setProperty(entry.getKey(), entry.getValue());
```
Comment (aiwenmo) [inline dinky-cdc/dinky-cdc-core/src/main/java/org/dinky/cdc/AbstractSinkBuilder.java:135]: Why set other keys that do not start with an attribute?

**Review by aiwenmo — COMMENTED** [review]
Thanks for your pull request.

File: dinky-cdc/dinky-cdc-core/src/main/java/org/dinky/cdc/AbstractSinkBuilder.java (hunk 1 above)
Comment (chenhaipeng) [reply dinky-cdc/dinky-cdc-core/src/main/java/org/dinky/cdc/AbstractSinkBuilder.java:594]: 有好几个KakfaSinkBuilder, KafkaSinkJsonBuilder ， 不放这里需要写好几次

File: dinky-cdc/dinky-cdc-core/src/main/java/org/dinky/cdc/AbstractSinkBuilder.java (hunk 2 above)
Comment (chenhaipeng) [reply dinky-cdc/dinky-cdc-core/src/main/java/org/dinky/cdc/AbstractSinkBuilder.java:135]: because there's no place in the constructor of kafkaSinkBuilder to set properties.
image

File: dinky-cdc/dinky-cdc-core/src/main/java/org/dinky/cdc/AbstractSinkBuilder.java (hunk 1 above)
Comment (aiwenmo) [reply dinky-cdc/dinky-cdc-core/src/main/java/org/dinky/cdc/AbstractSinkBuilder.java:594]: Add AbstractKafkaSinkBuilder.

Comment (chenhaipeng) [reply dinky-cdc/dinky-cdc-core/src/main/java/org/dinky/cdc/AbstractSinkBuilder.java:594]: > Add AbstractKafkaSinkBuilder.

it just a single method , Is it necessary to add an AbstractKafkaSinkBuilder class?

Comment (aiwenmo) [reply dinky-cdc/dinky-cdc-core/src/main/java/org/dinky/cdc/AbstractSinkBuilder.java:594]: If sinks other than kafka use this method, your current code logic is feasible.

File: dinky-cdc/dinky-cdc-core/src/main/java/org/dinky/cdc/AbstractSinkBuilder.java (hunk 2 above)
Comment (aiwenmo) [reply dinky-cdc/dinky-cdc-core/src/main/java/org/dinky/cdc/AbstractSinkBuilder.java:135]: Thx. I get it.

**Comment by aiwenmo** [comment]
#3874  will be fixed by #3889

**Comment by Zzm0809** [comment]
@chenhaipeng 你好, 请合并主仓库最新代码 解决 CI 过程出现的问题, 并将您的 Pr title 进行简单规范, 再次感谢您的贡献

**Comment by chenhaipeng** [comment]
> @chenhaipeng 你好, 请合并主仓库最新代码 解决 CI 过程出现的问题, 并将您的 Pr title 进行简单规范, 再次感谢您的贡献

OK

**Review by aiwenmo — APPROVED** [review]
LGTM

**Comment by chenhaipeng** [comment]
> @chenhaipeng 你好, 请合并主仓库最新代码 解决 CI 过程出现的问题, 并将您的 Pr title 进行简单规范, 再次感谢您的贡献

我已经重新合并了，pr comit title 简单修改了

File: dinky-core/src/main/java/org/dinky/job/builder/JobExecuteBuilder.java [hunk 3]
```diff
@@ -65,6 +65,8 @@ public void run() throws Exception {
                 }
                 GatewayResult gatewayResult = null;
                 config.addGatewayConfig(executor.getSetConfig());
+                config.addGatewayConfig(
+                        executor.getCustomTableEnvironment().getConfig().getConfiguration());
```
Comment (chenhaipeng) [inline dinky-core/src/main/java/org/dinky/job/builder/JobExecuteBuilder.java:69]: flink sql set 参数不生效，我加了这一行放到这里是否合理，麻烦确认下

**Comment by guojiew** [comment]
dinky-core/src/main/java/org/dinky/api/FlinkAPI.java构造函数的修改，导致主动触发savepoints的触发都报String index out of range: 0。。。
