### PR TITLE
[Fix-#2739] Fix bug that complete the missing path in auto.sh's CLASS_PATH

### LINKED ISSUE #2739: [Bug] [script] Missing "./extends/*" path in auto.sh's CLASS_PATH
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

Exception "java.lang.ClassNotFoundException: com.mysql.cj.jdbc.Dirver" occurs when mysql driver jar under **extends/** path.

### What you expected to happen

No exception occurs when dependencies jars under extends/ path.

### How to reproduce

Put dependencies jars under extends/ path, then start dinky.

### Anything else

_No response_

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by leeoo**
## Purpose of the pull request

Fix bug #2739.

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

### CODE REVIEW

File: script/bin/auto.sh [hunk 1]
```diff
@@ -5,7 +5,7 @@ FLINK_VERSION=${2:-1.18}
 JAR_NAME="dinky-admin"
 
 # Use FLINK_HOME:
-CLASS_PATH=".:./lib/*:config:./plugins/*:./customJar/*:./plugins/flink${FLINK_VERSION}/dinky/*:./plugins/flink${FLINK_VERSION}/*:./extends/flink${FLINK_VERSION}/dinky/*:./extends/flink${FLINK_VERSION}/*"
+CLASS_PATH=".:./lib/*:config:./extends/*:./plugins/*:./customJar/*:./plugins/flink${FLINK_VERSION}/dinky/*:./plugins/flink${FLINK_VERSION}/*:./extends/flink${FLINK_VERSION}/dinky/*:./extends/flink${FLINK_VERSION}/*"
```
Comment (Zzm0809) [inline script/bin/auto.sh:8]: ./extends/flink${FLINK_VERSION}/dinky/*:./extends/flink${FLINK_VERSION}/*

is repeat

**Review by gaoyan1998 — APPROVED** [review]
LGTM
