### PR TITLE
fixed bug "all ip port is not available" #3700 

### LINKED ISSUE #3700: [Bug] dinky can not get k8s flink operator executing result and the console threw error.
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

my dinky web ui is installed in the dockerdesktop software, k8s is installed in the same local area network; I can submit the flinksql job to the k8s flink operator, and the job is corrnect and running normally in flink cluster, but dinky console throw error "all ip port is not available ".

### What you expected to happen

I expecte the console can get normal response and no error; futhermore ,I can control the flink job in k8s by the dinky console; below,I provide some log information.

2024-08-11 16:59:18 [dinky] 2024-08-11 08:59:18.423   INFO    48 --- [nio-8888-exec-3] org.dinky.gateway.kubernetes.operator.KubetnetsApplicationOperatorGateway: ping ip port 
2024-08-11 16:59:18 [dinky] 2024-08-11 08:59:18.424   WARN    48 --- [nio-8888-exec-3] org.dinky.gateway.kubernetes.operator.KubetnetsApplicationOperatorGateway: ping ip port error
2024-08-11 16:59:18 java.lang.IllegalArgumentException: protocol = http host = null
2024-08-11 16:59:18     at sun.net.spi.DefaultProxySelector.select(DefaultProxySelector.java:177) ~[?:1.8.0_412]
2024-08-11 16:59:18     at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1156) ~[?:1.8.0_412]
2024-08-11 16:59:18     at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1056) ~[?:1.8.0_412]
2024-08-11 16:59:18     at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:990) ~[?:1.8.0_412]
2024-08-11 16:59:18     at cn.hutool.http.HttpConnection.connect(HttpConnection.java:387) ~[hutool-all-5.8.27.jar:5.8.27]
2024-08-11 16:59:18     at cn.hutool.http.HttpRequest.send(HttpRequest.java:1345) ~[hutool-all-5.8.27.jar:5.8.27]
2024-08-11 16:59:18     at cn.hutool.http.HttpRequest.doExecute(HttpRequest.java:1188) ~[hutool-all-5.8.27.jar:5.8.27]
2024-08-11 16:59:18     at cn.hutool.http.HttpRequest.execute(HttpRequest.java:1051) ~[hutool-all-5.8.27.jar:5.8.27]
2024-08-11 16:59:18     at cn.hutool.http.HttpRequest.execute(HttpRequest.java:1027) ~[hutool-all-5.8.27.jar:5.8.27]
2024-08-11 16:59:18     at cn.hutool.http.HttpUtil.get(HttpUtil.java:145) ~[hutool-all-5.8.27.jar:5.8.27]
2024-08-11 16:59:18     at org.dinky.gateway.kubernetes.operator.KubetnetsApplicationOperatorGateway.pingIpPort(KubetnetsApplicationOperatorGateway.java:218) ~[dinky-gateway-1.0.3.jar:?]
2024-08-11 16:59:18     at org.dinky.gateway.kubernetes.operator.KubetnetsApplicationOperatorGateway.getWebUrl(KubetnetsApplicationOperatorGateway.java:207) ~[dinky-gateway-1.0.3.jar:?]
2024-08-11 16:59:18     at org.dinky.gateway.kubernetes.operator.KubetnetsApplicationOperatorGateway.submitJar(KubetnetsApplicationOperatorGateway.java:132) ~[dinky-gateway-1.0.3.jar:?]
2024-08-11 16:59:18     at org.dinky.job.builder.JobTransBuilder.submitByGateway(JobTransBuilder.java:193) ~[dinky-core-1.0.3.jar:?]
2024-08-11 16:59:18     at org.dinky.job.builder.JobTransBuilder.processWithGateway(JobTransBuilder.java:109) ~[dinky-core-1.0.3.jar:?]
2024-08-11 16:59:18     at org.dinky.job.builder.JobTransBuilder.handleStatementSet(JobTransBuilder.java:81) ~[dinky-core-1.0.3.jar:?]
2024-08-11 16:59:18     at org.dinky.job.builder.JobTransBuilder.run(JobTransBuilder.java:70) ~[dinky-core-1.0.3.jar:?]
2024-08-11 16:59:18     at org.dinky.job.JobManager.executeSql(JobManager.java:361) ~[dinky-core-1.0.3.jar:?]
2024-08-11 16:59:18     at org.dinky.service.task.FlinkSqlTask.execute(FlinkSqlTask.java:68) ~[dinky-admin-1.0.3.jar:?]
2024-08-11 16:59:18     at org.dinky.service.impl.TaskServiceImpl.executeJob(TaskServiceImpl.java:194) ~[dinky-admin-1.0.3.jar:?]
2024-08-11 16:59:18     at org.dinky.service.impl.TaskServiceImpl$$FastClassBySpringCGLIB$$22087f7c.invoke(<generated>) ~[dinky-admin-1.0.3.jar:?]
2024-08-11 16:59:18     at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.3.27.jar:5.3.27]
2024-08-11 16:59:18     at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793) ~[spring-aop-5.3.27.jar:5.3.27]
2024-08-11 16:59:18     at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.3.27.jar:5.3.27]
2024-08-11 16:59:18     at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763) ~[spring-aop-5.3.27.jar:5.3.27]
2024-08-11 16:59:18     at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:89) ~[spring-aop-5.3.27.jar:5.3.27]
2024-08-11 16:59:18     at org.dinky.aop.ProcessAspect.processStepAround(ProcessAspect.java:110) ~[dinky-admin-1.0.3.jar:?]
2024-08-11 16:59:18     at sun.reflect.GeneratedMethodAccessor775.invoke(Unknown Source) ~[?:?]
2024-08-11 16:59:18     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_412]
2024-08-11 16:59:18     at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_412]
2024-08-11 16:59:18     at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:634) ~[spring-aop-5.3.27.jar:5.3.27]
2024-08-11 16:59:18     at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:624) ~[spring-aop-5.3.27.jar:5.3.27]
2024-08-11 16:59:18     at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:72) ~[spring-aop-5.3.27.jar:5.3.27]
2024-08-11 16:59:18     at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175) ~[spring-aop-5.3.27.jar:5.3.27]
2024-08-11 16:59:18     at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763) ~[spring-aop-5.3.27.jar:5.3.27]
2024-08-11 16:59:18     at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97) ~[spring-aop-5.3.27.jar:5.3.27]
2024-08-11 16:59:18     at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.27.jar:5.3.27]
2024-08-11 16:59:18     at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763) ~[spring-aop-5.3.27.jar:5.3.27]
2024-08-11 16:59:18     at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708) ~[spring-aop-5.3.27.jar:5.3.27]
2024-08-11 16:59:18     at org.dinky.service.impl.TaskServiceImpl$$EnhancerBySpringCGLIB$$13b5ed8.executeJob(<generated>) ~[dinky-admin-1.0.3.jar:?]
2024-08-11 16:59:18     at org.dinky.service.impl.TaskServiceImpl.submitTask(TaskServiceImpl.java:322) ~[dinky-admin-1.0.3.jar:?]
2024-08-11 16:59:18     at org.dinky.service.impl.TaskServiceImpl$$FastClassBySpringCGLIB$$22087f7c.invoke(<generated>) ~[dinky-admin-1.0.3.jar:?]
2024-08-11 16:59:18     at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.3.27.jar:5.3.27]
2024-08-11 16:59:18     at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793) ~[spring-aop-5.3.27.jar:5.3.27]
2024-08-11 16:59:18     at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.3.27.jar:5.3.27]
2024-08-11 16:59:18     at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763) ~[spring-aop-5.3.27.jar:5.3.27]
2024-08-11 16:59:18     at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:89) ~[spring-aop-5.3.27.jar:5.3.27]
2024-08-11 16:59:18     at org.dinky.aop.UdfClassLoaderAspect.round(UdfClassLoaderAspect.java:55) ~[dinky-admin-1.0.3.jar:?]
2024-08-11 16:59:18     at sun.reflect.GeneratedMethodAccessor129.invoke(Unknown Source) ~[?:?]
2024-08-11 16:59:18     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_412]
2024-08-11 16:59:18     at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_412]
2024-08-11 16:59:18     at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:634) ~[spring-aop-5.3.27.jar:5.3.27]
2024-08-11 16:59:18     at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:624) ~[spring-aop-5.3.27.jar:5.3.27]
2024-08-11 16:59:18     at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:72) ~[spring-aop-5.3.27.jar:5.3.27]
2024-08-11 16:59:18     at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.27.jar:5.3.27]
2024-08-11 16:59:18     at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763) ~[spring-aop-5.3.27.jar:5.3.27]
2024-08-11 16:59:18     at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97) ~[spring-aop-5.3.27.jar:5.3.27]
2024-08-11 16:59:18     at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.27.jar:5.3.27]
2024-08-11 16:59:18     at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763) ~[spring-aop-5.3.27.jar:5.3.27]
2024-08-11 16:59:18     at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708) ~[spring-aop-5.3.27.jar:5.3.27]
2024-08-11 16:59:18     at org.dinky.service.impl.TaskServiceImpl$$EnhancerBySpringCGLIB$$13b5ed8.submitTask(<generated>) ~[dinky-admin-1.0.3.jar:?]
2024-08-11 16:59:18     at org.dinky.controller.TaskController.submitTask(TaskController.java:82) ~[dinky-admin-1.0.3.jar:?]
2024-08-11 16:59:18     at org.dinky.controller.TaskController$$FastClassBySpringCGLIB$$5b68bd32.invoke(<generated>) ~[dinky-admin-1.0.3.jar:?]
2024-08-11 16:59:18     at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.3.27.jar:5.3.27]
2024-08-11 16:59:18     at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793) ~[spring-aop-5.3.27.jar:5.3.27]
2024-08-11 16:59:18     at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.3.27.jar:5.3.27]
2024-08-11 16:59:18     at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763) ~[spring-aop-5.3.27.jar:5.3.27]
2024-08-11 16:59:18     at org.springframework.aop.framework.adapter.AfterReturningAdviceInterceptor.invoke(AfterReturningAdviceInterceptor.java:57) ~[spring-aop-5.3.27.jar:5.3.27]
2024-08-11 16:59:18     at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.27.jar:5.3.27]
2024-08-11 16:59:18     at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763) ~[spring-aop-5.3.27.jar:5.3.27]
2024-08-11 16:59:18     at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:89) ~[spring-aop-5.3.27.jar:5.3.27]
2024-08-11 16:59:18     at org.dinky.aop.ProcessAspect.processAround(ProcessAspect.java:73) ~[dinky-admin-1.0.3.jar:?]
2024-08-11 16:59:18     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_412]
2024-08-11 16:59:18     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_412]
2024-08-11 16:59:18     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_412]
2024-08-11 16:59:18     at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_412]
2024-08-11 16:59:18     at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:634) ~[spring-aop-5.3.27.jar:5.3.27]
2024-08-11 16:59:18     at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:624) ~[spring-aop-5.3.27.jar:5.3.27]
2024-08-11 16:59:18     at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:72) ~[spring-aop-5.3.27.jar:5.3.27]
2024-08-11 16:59:18     at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175) ~[spring-aop-5.3.27.jar:5.3.27]
2024-08-11 16:59:18     at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763) ~[spring-aop-5.3.27.jar:5.3.27]
2024-08-11 16:59:18     at org.springframework.aop.aspectj.AspectJAfterThrowingAdvice.invoke(AspectJAfterThrowingAdvice.java:64) ~[spring-aop-5.3.27.jar:5.3.27]
2024-08-11 16:59:18     at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175) ~[spring-aop-5.3.27.jar:5.3.27]
2024-08-11 16:59:18     at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763) ~[spring-aop-5.3.27.jar:5.3.27]
2024-08-11 16:59:18     at org.springframework.aop.framework.adapter.AfterReturningAdviceInterceptor.invoke(AfterReturningAdviceInterceptor.java:57) ~[spring-aop-5.3.27.jar:5.3.27]
2024-08-11 16:59:18     at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175) ~[spring-aop-5.3.27.jar:5.3.27]
2024-08-11 16:59:18     at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763) ~[spring-aop-5.3.27.jar:5.3.27]
2024-08-11 16:59:18     at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97) ~[spring-aop-5.3.27.jar:5.3.27]
2024-08-11 16:59:18     at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.27.jar:5.3.27]
2024-08-11 16:59:18     at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763) ~[spring-aop-5.3.27.jar:5.3.27]
2024-08-11 16:59:18     at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708) ~[spring-aop-5.3.27.jar:5.3.27]
2024-08-11 16:59:18     at org.dinky.controller.TaskController$$EnhancerBySpringCGLIB$$a192f113.submitTask(<generated>) ~[dinky-admin-1.0.3.jar:?]
2024-08-11 16:59:18     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_412]
2024-08-11 16:59:18     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_412]
2024-08-11 16:59:18     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_412]
2024-08-11 16:59:18     at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_412]
2024-08-11 16:59:18     at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205) ~[spring-web-5.3.27.jar:5.3.27]
2024-08-11 16:59:18     at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150) ~[spring-web-5.3.27.jar:5.3.27]
2024-08-11 16:59:18     at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117) ~[spring-webmvc-5.3.27.jar:5.3.27]
2024-08-11 16:59:18     at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895) ~[spring-webmvc-5.3.27.jar:5.3.27]
2024-08-11 16:59:18     at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808) ~[spring-webmvc-5.3.27.jar:5.3.27]
2024-08-11 16:59:18     at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-5.3.27.jar:5.3.27]
2024-08-11 16:59:18     at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1072) ~[spring-webmvc-5.3.27.jar:5.3.27]
2024-08-11 16:59:18     at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:965) ~[spring-webmvc-5.3.27.jar:5.3.27]
2024-08-11 16:59:18     at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006) ~[spring-webmvc-5.3.27.jar:5.3.27]
2024-08-11 16:59:18     at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898) ~[spring-webmvc-5.3.27.jar:5.3.27]
2024-08-11 16:59:18     at javax.servlet.http.HttpServlet.service(HttpServlet.java:529) ~[tomcat-embed-core-9.0.74.jar:4.0.FR]
2024-08-11 16:59:18     at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883) ~[spring-webmvc-5.3.27.jar:5.3.27]
2024-08-11 16:59:18     at javax.servlet.http.HttpServlet.service(HttpServlet.java:623) ~[tomcat-embed-core-9.0.74.jar:4.0.FR]
2024-08-11 16:59:18     at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:209) ~[tomcat-embed-core-9.0.74.jar:9.0.74]
2024-08-11 16:59:18     at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153) ~[tomcat-embed-core-9.0.74.jar:9.0.74]
2024-08-11 16:59:18     at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51) ~[tomcat-embed-websocket-9.0.74.jar:9.0.74]
2024-08-11 16:59:18     at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178) ~[tomcat-embed-core-9.0.74.jar:9.0.74]
2024-08-11 16:59:18     at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153) ~[tomcat-embed-core-9.0.74.jar:9.0.74]
2024-08-11 16:59:18     at org.springframework.web.filter.CorsFilter.doFilterInternal(CorsFilter.java:91) ~[spring-web-5.3.27.jar:5.3.27]
2024-08-11 16:59:18     at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.27.jar:5.3.27]
2024-08-11 16:59:18     at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178) ~[tomcat-embed-core-9.0.74.jar:9.0.74]
2024-08-11 16:59:18     at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153) ~[tomcat-embed-core-9.0.74.jar:9.0.74]
2024-08-11 16:59:18     at com.alibaba.druid.support.http.WebStatFilter.doFilter(WebStatFilter.java:114) ~[druid-1.2.15.jar:?]
2024-08-11 16:59:18     at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178) ~[tomcat-embed-core-9.0.74.jar:9.0.74]
2024-08-11 16:59:18     at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153) ~[tomcat-embed-core-9.0.74.jar:9.0.74]
2024-08-11 16:59:18     at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) ~[spring-web-5.3.27.jar:5.3.27]
2024-08-11 16:59:18     at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.27.jar:5.3.27]
2024-08-11 16:59:18     at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178) ~[tomcat-embed-core-9.0.74.jar:9.0.74]
2024-08-11 16:59:18     at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153) ~[tomcat-embed-core-9.0.74.jar:9.0.74]
2024-08-11 16:59:18     at cn.dev33.satoken.filter.SaPathCheckFilterForServlet.doFilter(SaPathCheckFilterForServlet.java:55) ~[sa-token-spring-boot-starter-1.37.0.jar:?]
2024-08-11 16:59:18     at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178) ~[tomcat-embed-core-9.0.74.jar:9.0.74]
2024-08-11 16:59:18     at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153) ~[tomcat-embed-core-9.0.74.jar:9.0.74]
2024-08-11 16:59:18     at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) ~[spring-web-5.3.27.jar:5.3.27]
2024-08-11 16:59:18     at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.27.jar:5.3.27]
2024-08-11 16:59:18     at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178) ~[tomcat-embed-core-9.0.74.jar:9.0.74]
2024-08-11 16:59:18     at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153) ~[tomcat-embed-core-9.0.74.jar:9.0.74]
2024-08-11 16:59:18     at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:96) ~[spring-boot-actuator-2.7.11.jar:2.7.11]
2024-08-11 16:59:18     at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.27.jar:5.3.27]
2024-08-11 16:59:18     at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178) ~[tomcat-embed-core-9.0.74.jar:9.0.74]
2024-08-11 16:59:18     at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153) ~[tomcat-embed-core-9.0.74.jar:9.0.74]
2024-08-11 16:59:18     at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) ~[spring-web-5.3.27.jar:5.3.27]
2024-08-11 16:59:18     at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.27.jar:5.3.27]
2024-08-11 16:59:18     at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178) ~[tomcat-embed-core-9.0.74.jar:9.0.74]
2024-08-11 16:59:18     at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153) ~[tomcat-embed-core-9.0.74.jar:9.0.74]
2024-08-11 16:59:18     at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167) ~[tomcat-embed-core-9.0.74.jar:9.0.74]
2024-08-11 16:59:18     at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90) ~[tomcat-embed-core-9.0.74.jar:9.0.74]
2024-08-11 16:59:18     at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:481) ~[tomcat-embed-core-9.0.74.jar:9.0.74]
2024-08-11 16:59:18     at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:130) ~[tomcat-embed-core-9.0.74.jar:9.0.74]
2024-08-11 16:59:18     at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93) ~[tomcat-embed-core-9.0.74.jar:9.0.74]
2024-08-11 16:59:18     at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) ~[tomcat-embed-core-9.0.74.jar:9.0.74]
2024-08-11 16:59:18     at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) ~[tomcat-embed-core-9.0.74.jar:9.0.74]
2024-08-11 16:59:18     at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:389) ~[tomcat-embed-core-9.0.74.jar:9.0.74]
2024-08-11 16:59:18     at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63) ~[tomcat-embed-core-9.0.74.jar:9.0.74]
2024-08-11 16:59:18     at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:926) ~[tomcat-embed-core-9.0.74.jar:9.0.74]
2024-08-11 16:59:18     at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1791) ~[tomcat-embed-core-9.0.74.jar:9.0.74]
2024-08-11 16:59:18     at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52) ~[tomcat-embed-core-9.0.74.jar:9.0.74]
2024-08-11 16:59:18     at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) ~[tomcat-embed-core-9.0.74.jar:9.0.74]
2024-08-11 16:59:18     at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) ~[tomcat-embed-core-9.0.74.jar:9.0.74]
2024-08-11 16:59:18     at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-embed-core-9.0.74.jar:9.0.74]
2024-08-11 16:59:18     at java.lang.Thread.run(Thread.java:750) ~[?:1.8.0_412]
2024-08-11 16:59:18 [dinky] 2024-08-11 08:59:18.443  ERROR    48 --- [nio-8888-exec-3] org.dinky.aop.exception.UnKnownExceptionHandler: java.lang.Exception: Exception in executing FlinkSQL:
2024-08-11 16:59:18 1     INSERT INTO datagen_source_mysql
2024-08-11 16:59:18 2     SELECT
2024-08-11 16:59:18 3        id,
2024-08-11 16:59:18 4        name 
2024-08-11 16:59:18 5     from datagen_source
2024-08-11 16:59:18 
2024-08-11 16:59:18 all ip port is not available 
2024-08-11 16:59:18 java.lang.RuntimeException: java.lang.Exception: Exception in executing FlinkSQL:
2024-08-11 16:59:18 1     INSERT INTO datagen_source_mysql
2024-08-11 16:59:18 2     SELECT
2024-08-11 16:59:18 3        id,
2024-08-11 16:59:18 4        name 
2024-08-11 16:59:18 5     from datagen_source
2024-08-11 16:59:18 
2024-08-11 16:59:18 all ip port is not available 

### How to reproduce

dinky-version: 1.0.3
flink-version: 1.17
k8s: 1.20.11
dinky-image: dinkydocker/dinky-standalone-server:1.0.3-flink1.17
dockerdesktop: 4.30.0

flinksql content： 
`drop table IF EXISTS datagen_source;
--创建源表datagen_source
CREATE TABLE datagen_source(
  id  BIGINT,
  name STRING
) WITH (
  'connector' = 'datagen'
);

drop table IF EXISTS datagen_source_mysql;
--创建结果表datagen_source_mysql
CREATE  TABLE datagen_source_mysql(
   id  BIGINT,
   name STRING
) WITH (
   'connector' = 'jdbc',
   'url' = 'jdbc:mysql://192.168.44.111:3306/test',
   'table-name' = 'datagen_source_mysql',
   'username' = 'dinky',
   'password' = '123456'
);
--将源表数据插入到结果表
INSERT INTO datagen_source_mysql
SELECT
   id,
   name 
from datagen_source;`

### Anything else

_No response_

### Version

1.0.2

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by soulmz**
## Purpose of the pull request

close #3700 

## Brief change log

- fixed bug "all ip port is not available" , 获取 k8s service list 列表失败
- modify  kubernetes 拼写错误。

## Verify this pull request

- 因环境因素，本地和线上代码已经替换了 gateway jar 包，运行正常。

image

### CODE REVIEW

File: build-extr.sh [hunk 1]
```diff
@@ -56,7 +56,7 @@ while getopts "j:f:" opt; do
 done
 
 # 构建命令
-CMD="./mvnw clean package -Dmaven.test.skip=true -P prod,${JDK_VERSION},flink-single-version,aliyun,${FLINK_VERSION},web"
+CMD="./mvnw clean package -Dmaven.test.skip=true -P prod,${JDK_VERSION},flink-single-version,scala-2.12,aliyun,${FLINK_VERSION},web"
```
Comment (gaoyan1998) [inline build-extr.sh]: dev has deleted the scala version selection. The default is 2.12. There is no need to add it here.

**Review by gaoyan1998 — CHANGES_REQUESTED** [review]

**Review by gaoyan1998 — APPROVED** [review]
LGTM
